language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  directories:
  - $HOME/.m2

install: echo $TESTVAL

script: mvn install -Pbuild-docker-image

branches:
  only:
    - master
