language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true

addons:
  sonarqube:
    organization: "cpollet-github"
    token:
      secure: $SONARQUBE_TOKEN

script:
 - mvn package -Pbuild-docker-image
 - mvn -f pom-sonar.pom -P sonar-java org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push cpollet/net.cpollet.itinerants-mailer-daemon:latest
  - docker push cpollet/net.cpollet.itinerants-webapp:latest
  - docker push cpollet/net.cpollet.itinerants-webservice-web:latest
  - curl "https://webhook.cpollet.io/hooks/net.cpollet.itinerants:redeploy?token=$WEBHOOK_TOKEN"

branches:
  only:
    - master
