export const FUTURE_EVENTS_FETCH = 'FUTURE_EVENTS_FETCH';
export const FUTURE_EVENTS_FETCH_SUCCESS = 'FUTURE_EVENTS_FETCH_SUCCESS';
export const FUTURE_EVENTS_FETCH_ERROR = 'FUTURE_EVENTS_FETCH_ERROR';

export const PROFILE_FETCH = 'PROFILE_FETCH';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_ERROR = 'PROFILE_FETCH_ERROR';

export const ATTENDANCES_FETCH_SUCCESS = 'ATTENDANCES_FETCH_SUCCESS';

export const AVAILABILITIES_FETCH_SUCCESS = 'AVAILABILITIES_FETCH_SUCCESS';
export const AVAILABILITY_TOGGLE = 'AVAILABILITY_TOGGLE';
export const AVAILABILITY_INVALIDATE_STATE = 'AVAILABILITY_INVALIDATE_STATE'; // could be merged with AVAILABILITY_TOGGLE
export const AVAILABILITY_DECREASE_SAVE_TIMEOUT = 'AVAILABILITY_DECREASE_SAVE_TIMEOUT';
export const AVAILABILITY_SAVE_START = 'AVAILABILITY_SAVE_START';
export const AVAILABILITY_SAVE_SUCCESS = 'AVAILABILITY_SAVE_SUCCESS';
export const AVAILABILITY_SAVE_RETRY = 'AVAILABILITY_SAVE_RETRY';
export const AVAILABILITY_SAVE_ERROR = 'AVAILABILITY_SAVE_ERROR';

export const PLANNING_TOGGLE_EVENT_SELECTION = 'PLANNING_TOGGLE_EVENT_SELECTION';
export const PLANNING_PROPOSAL_FETCH = 'PLANNING_PROPOSAL_FETCH';
export const PLANNING_PROPOSAL_FETCH_SUCCESS = 'PLANNING_PROPOSAL_FETCH_SUCCESS';
export const PLANNING_TOGGLE_PERSON_SELECTION = 'PLANNING_TOGGLE_PERSON_SELECTION';
export const PLANNING_SAVE_START = 'PLANNING_SAVE_START';
export const PLANNING_SAVE_SUCCESS = 'PLANNING_SAVE_SUCCESS';

export const PEOPLE_FETCH_SUCCESS = 'PEOPLE_FETCH_SUCCESS';

export const PROFILE_SAVE_START = 'PROFILE_SAVE_START';
export const PROFILE_SAVE_SUCCESS = 'PROFILE_SAVE_SUCCESS';
export const PROFILE_SAVE_ERROR_VALIDATION = 'PROFILE_SAVE_ERROR_VALIDATION';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const LOGIN_RESET_FORM = 'LOGIN_RESET_FORM';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR_EXPIRED = 'LOGIN_ERROR_EXPIRED';
export const LOGIN_ERROR_INVALID = 'LOGIN_ERROR_INVALID';

export const LOGOUT = 'LOGOUT';

export const RESET_PASSWORD_ERROR_USERNAME_EMPTY = 'RESET_PASSWORD_ERROR_USERNAME_EMPTY';
export const RESET_PASSWORD_ERROR_PASSWORD_TOO_SHORT = 'RESET_PASSWORD_ERROR_PASSWORD_TOO_SHORT';
export const RESET_PASSWORD_PASSWORDS_MATCH = 'RESET_PASSWORD_PASSWORDS_MATCH';
export const RESET_PASSWORD_TOKEN_VALID = 'RESET_PASSWORD_TOKEN_VALID';
export const RESET_PASSWORD_TOKEN_SENT = 'RESET_PASSWORD_TOKEN_SENT';

export const SERVER_ERROR = 'SERVER_ERROR';
export const SERVER_ERROR_RESET = 'SERVER_ERROR_RESET';
